#!/usr/bin/env bash

# Include essentials file(s).
source "${DDEV_APPROOT}/.ddev/commands/host/_bash/bash"

# File paths.
FROM_PATH="${DDEV_APPROOT}/.ddev/droptica/db"

# Add info about restoring.
printf "%s[%s] %sRestoring %sdatabase%s...\n" "${aqua}" "${DDEV_SITENAME_APP}" "${no_color}" "${lime}" "${no_color}"

# Check if users passed one argument.
if [ "$#" -ne 1 ]; then
  # Find any file starting with "database" and sort if by time.
  DB_FILE=$(find "${FROM_PATH}" -type f -name "database*" -exec ls -t {} + 2>/dev/null | head -n1)

  # Check if we have found any database.
  if [ -n "$DB_FILE" ]; then
    # Add info about which file is being used.
    printf "%s[%s] %sUsing %s%s%s file, starting import...\n" "${aqua}" "${DDEV_SITENAME_APP}" "${no_color}" "${lime}" "$(basename "$DB_FILE")" "${no_color}"

    # Then simply restore the latest database dump.
    ddev import-db --database=db --file="${DB_FILE}"
  else
    # Add info about non-existing files.
    printf "%s[%s] %sWe couldn't find any database file, skipping db-restore...\n" "${aqua}" "${DDEV_SITENAME_APP}" "${no_color}"
    exit;
  fi
else
  # If user did pass one argument, check if that file exists.
  if [ -f "${FROM_PATH}/$1" ]; then
    # Restore .sql from local dump.
    ddev import-db --database=db --file="${FROM_PATH}"/"$1"
  else
    # Add info about non-existing files.
    printf "%s[%s] %sWe couldn't find '%s' database file%s!\n" "${aqua}" "${DDEV_SITENAME_APP}" "${red}" "$1" "${no_color}"

    # Skip rest of the code.
    exit 1;
  fi
fi

# Get status code from current command.
status=$?

# Check status code from previous command.
if [ $status != 0 ]; then
  # Add info some errors that were detected.
  printf "%s[%s] %sThere was an error in the db-import, check them before you can continue.%s\n" "${aqua}" "${DDEV_SITENAME_APP}" "${red}" "${no_color}"

  # Return error for other scripts to handle.
  exit 1;
fi

# Add ending info about db import status.
printf "%s[%s] %sSuccessfully restored %sdatabase%s!\n" "${aqua}" "${DDEV_SITENAME_APP}" "${no_color}" "${lime}" "${no_color}"
